name: Deploy Nomad Job
on: [push]
jobs:
  deploy:
    name: Nomad Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Connect Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_KEY }} 
          version: 1.14.0

      - name: Deploy with Nomad
        uses: qazz92/nomad-deploy
        with:
          # token: ${{ secrets.YOUR_NOMAD_SECRET }}
          address: ${{ secrets.NOMAD_ADDR }}
          job: |-
          # config: path/to/your/levant/config/file
