name: nomad-pack

on:
  - push

jobs:
  setup-nomad-pack:
    runs-on: ubuntu-latest
    name: Run Nomad Pack
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy nomad
        uses: rluisr/nomad-actions@master
          
      - name: Deploy
        run: |
          export NOMAD_ADDR="https://nomad.leandroaurelio.com"
          # Certifique-se de que a URL esteja correta para o seu proxy Nginx
          nomad job plan ghost.nomad
          nomad job run ghost.nomad
          nomad status
        env:
          NOMAD_ADDR: "https://nomad.leandroaurelio.com"
