name: nomad-pack

on:
  - push

jobs:
  setup-nomad-pack:
    runs-on: ubuntu-latest
    name: Run Nomad Pack
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run `nomad-pack run` for `simple_service`
        id: run
        run: "nomad-pack run ./packs/simple_service"
        env:
          NOMAD_ADDR: "${{ secrets.NOMAD_ADDR }}"
          NOMAD_JOB: ghost.nomad
          # NOMAD_TOKEN: "${{ secrets.NOMAD_TOKEN }}"
        continue-on-error: true
