name: nomad-pack

on:
  - push

jobs:
  setup-nomad-pack:
    runs-on: ubuntu-latest
    name: Run Nomad Pack
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Connect Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_KEY }} 
          version: 1.14.0

      - name: Deploy nomad
        uses: rluisr/nomad-actions@master
          
      - name: Deploy
        run: |
          export NOMAD_ADDR=${{ secrets.NOMAD_ADDR }}
          nomad job plan ghost.nomad
          # plan_output=$(nomad job plan ghost.nomad)
          # echo "$plan_output"
          # if echo "$plan_output" | grep -q "job modify given matches"; then
          # nomad job run -check-index $(echo "$plan_output" | awk '{print $5}') ghost.nomad
          # else
          # echo "Job plan has changed since last run. Please review and modify the job accordingly."
          # fi
          nomad status
          nomad job run ghost.nomad
          # nomad job plan ghost.nomad
          # nomad job run ghost.nomad
          # nomad job plan ghost.nomad
          # or nomad-pack run .
        env:
          NOMAD_ADDR: "{{ secrets.NOMAD_ADDR }}"
