name: CI-CD
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:

  CD:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Connect Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_KEY }} 
          version: 1.14.0

      - name: Setup `nomad-pack`
        # TODO: define `v1`
        uses: hashicorp/setup-nomad-pack@v1
        id: setup
        with:
          version: "0.0.1-techpreview2" # or `latest`

      - name: Run `nomad-pack info` for `ghost`
        id: info
        run: "nomad-pack info ghost #./packs/simple_service"

      - name: Run `nomad-pack run` for ghost #`simple_service`
        id: run
        run: "nomad-pack run ghost #./packs/simple_service"
        env:
          NOMAD_ADDR: "${{ secrets.NOMAD_ADDR }}"
        continue-on-error: true
