name: nomad-pack

on:
  - push

jobs:
  setup-nomad-pack:
    runs-on: ubuntu-latest
    name: Run Nomad Pack
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Connect Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_KEY }} 
          version: 1.14.0

      - name: Deploy nomad
        uses: rluisr/nomad-actions@master
          
      - name: Deploy
        run: |
          export NOMAD_ADDR=${{ secrets.NOMAD_ADDR }}
          nomad status
          nomad job run ghost.nomad
          # nomad job plan ghost.nomad
          # or nomad-pack run .
        env:
          NOMAD_ADDR: "{{ secrets.NOMAD_ADDR }}"
