name: nomad-pack

on:
  push:

jobs:
  setup-nomad-pack:
    runs-on: ubuntu-latest
    name: Run Nomad Pack
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy nomad
        uses: rluisr/nomad-actions@master

      - name: Deploy
        run: |
          export NOMAD_ADDR="https://nomad.leandroaurelio.com"
          
          # Planeja o job e captura o Job Modify Index
          INDEX=$(nomad job plan ghost.nomad | grep "Job Modify Index" | awk '{print $4}')
          echo "Job Modify Index: $INDEX"
          
          # Executa o job com o índice capturado
          nomad job run -check-index $INDEX ghost.nomad
          
          # Exibe o status do job
          nomad status
        env:
          NOMAD_ADDR: "https://nomad.leandroaurelio.com"
