name: nomad-pack

on:
  push:
    paths:
      - 'ghost.nomad'
      - 'images/**'

jobs:
  setup-nomad-pack:
    runs-on: ubuntu-latest
    name: Run Nomad Pack
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG="leandroaurelio/ghost:${{ github.run_number }}"
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

          # Tag the image as 'latest'
          docker tag $IMAGE_TAG leandroaurelio/ghost:latest
          docker push leandroaurelio/ghost:latest

      - name: Deploy nomad
        uses: rluisr/nomad-actions@master

      - name: Deploy
        run: |
          export NOMAD_ADDR="https://nomad.leandroaurelio.com"

          # Substituir placeholders pelos secrets
          sed -i "s|__SITE_URL__|${{ secrets.SITE_URL }}|g" ghost.nomad
          sed -i "s|__USER_MAIL__|${{ secrets.USER_MAIL }}|g" ghost.nomad
          sed -i "s|__USER_PASSWORD__|${{ secrets.USER_PASSWORD }}|g" ghost.nomad
          sed -i "s|__MYSQL_ROOT_PASSWORD__|${{ secrets.MYSQL_ROOT_PASSWORD }}|g" ghost.nomad
          sed -i "s|__MYSQL_DATABASE__|${{ secrets.MYSQL_DATABASE }}|g" ghost.nomad
          sed -i "s|__MYSQL_USER__|${{ secrets.MYSQL_USER }}|g" ghost.nomad
          sed -i "s|__MYSQL_PASSWORD__|${{ secrets.MYSQL_PASSWORD }}|g" ghost.nomad
          
          # Planeja o job e captura o Job Modify Index
          INDEX=$(nomad job plan ghost.nomad | grep "Job Modify Index" | awk '{print $4}')
          echo "Job Modify Index: $INDEX"
          
          # Executa o job com o índice capturado
          nomad job run -check-index $INDEX ghost.nomad
          
          # Exibe o status do job
          nomad status
        env:
          NOMAD_ADDR: "https://nomad.leandroaurelio.com"
