name: Publish Blog Posts

on:
  push:
    paths:
      - 'texts/**'
      - 'images/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install pyjwt

    - name: Check GHOST_ADMIN_API_KEY
      run: echo "GHOST_ADMIN_API_KEY=${{ secrets.GHOST_ADMIN_API_KEY }}"

    - name: Generate JWT token for Ghost API
      run: |
        JWT_TOKEN=$(python3 generate_jwt.py "${{ secrets.GHOST_ADMIN_API_KEY }}")
        echo "JWT_TOKEN=$JWT_TOKEN" >> $GITHUB_ENV
        echo "JWT_TOKEN=$JWT_TOKEN"

    - name: Publish to Ghost via API
      run: |
        for file in $(ls -t texts/*.json); do  # Ordena por data de modificação
          if [ -f "$file" ]; then
            echo "Publishing $file"
            response=$(curl -s -X POST "https://blog.leandroaurelio.com/ghost/api/admin/posts/" \
              -H "Authorization: Ghost $JWT_TOKEN" \
              -H "Content-Type: application/json" \
              -d @"$file")
            echo "Response: $response"
        
            if echo "$response" | grep -q "ValidationError"; then
              echo "Error publishing $file: Validation failed"
              continue
            else
              echo "Published $file successfully"
              break
            fi
          fi
        done