name: Publish Blog Posts

on:
  push:
    paths:
      - 'texts/**'
      - 'images/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install pyjwt

    - name: Check GHOST_ADMIN_API_KEY
      run: echo "GHOST_ADMIN_API_KEY=${{ secrets.GHOST_ADMIN_API_KEY }}"

    - name: Generate JWT token for Ghost API
      run: |
        JWT_TOKEN=$(python3 generate_jwt.py "${{ secrets.GHOST_ADMIN_API_KEY }}")
        echo "JWT_TOKEN=$JWT_TOKEN" >> $GITHUB_ENV
        echo "JWT_TOKEN=$JWT_TOKEN"

    - name: Publish to Ghost via API
      run: |
        for file in texts/*.json; do
          if [ -f "$file" ]; then
            curl -X POST "https://blog.leandroaurelio.com/ghost/api/admin/posts/" \
              -H "Authorization: Ghost $JWT_TOKEN" \
              -H "Content-Type: application/json" \
              -d @"$file"
          fi
        done
