name: Publish Blog Posts

on:
  push:
    paths:
      - 'texts/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Publish to Ghost via API
      run: |
        for file in texts/*.md; do
          curl -X POST "$GHOST_API_URL/ghost/api/v3/content/posts/" \
            -H "Authorization: Ghost $GHOST_ADMIN_API_KEY" \
            -F "posts=@$file"
        done
